# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Knjiga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='prazno', max_length=256)),
                ('autor', models.CharField(default='prazno', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='prazno', max_length=50)),
                ('prezime', models.CharField(default='prazno', max_length=100)),
                ('uloga', models.CharField(default='prezno', max_length=256)),
                ('datum_rodjenja', models.DateTimeField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Primerak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('knjiga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Knjiga')),
            ],
        ),
        migrations.CreateModel(
            name='Zaduzenje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datun_iznajmljivanja', models.DateField(blank=True)),
                ('datum_vracanja', models.DateField(blank=True)),
                ('korisnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Korisnik')),
                ('primerak', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Primerak')),
            ],
        ),
        migrations.AddField(
            model_name='primerak',
            name='korisnik',
            field=models.ManyToManyField(through='korisnik.Zaduzenje', to='korisnik.Korisnik'),
        ),
    ]
