# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-23 18:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0002_auto_20170923_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='datum_rodjenja',
        ),
    ]
