# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 18:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0003_remove_korisnik_datum_rodjenja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='korisnik',
            name='ime',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='prezime',
        ),
        migrations.RemoveField(
            model_name='korisnik',
            name='uloga',
        ),
        migrations.AddField(
            model_name='korisnik',
            name='adresa',
            field=models.CharField(blank=True, default='prazno', max_length=256),
        ),
        migrations.AddField(
            model_name='korisnik',
            name='datum_rodjenja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaduzenje',
            name='datum_vracanja',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='zaduzenje',
            name='datun_iznajmljivanja',
            field=models.DateField(auto_now_add=True),
        ),
    ]
