# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 23:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0006_auto_20170926_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaduzenje',
            name='korisnik',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Korisnik'),
        ),
    ]
