# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 14:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('korisnik', '0007_auto_20170926_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zaduzenje',
            name='primerak',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='korisnik.Primerak'),
        ),
    ]
